insert into USER_TABLE values (1,'123','@spacemila');
insert into USER_TABLE values (2,'321','@snezzzzz');


insert into NOTES_TABLE values (1, NOW () ,1,'Libraries were full of ideas—perhaps the most dangerous and powerful of all weapons.','Sarah J. Maas',1,2);
insert into NOTES_TABLE values (2, NOW () ,3,'Behind this mask there is more than just flesh. Beneath this mask there is an idea... and ideas are bulletproof.',' Alan Moore',3,2);
insert into NOTES_TABLE values (3, NOW () ,2,'Ideas are easy. It''s the execution of ideas that really separates the sheep from the goats.','Sue Grafton',1,2);
insert into NOTES_TABLE values (4, NOW () ,2,'Daring ideas are like chessmen moved forward. They may be beaten, but they may start a winning game.','Johann Wolfgang von Goethe',1,2);
insert into NOTES_TABLE values (5, NOW () ,3,'For books are not absolutely dead things, but do contain a potency of life in them to be as active as that soul was whose progeny they are; nay, they do preserve as in a vial the purest efficacy and extraction of that living intellect that bred them','John Milton',1,2);
insert into NOTES_TABLE values (6, NOW () ,4,'Books are always obviously having conversations with other books, and some times they''re amiable and sometimes not.','China Mieville,',1,2);
insert into NOTES_TABLE values (7, NOW () ,2,'An idea that is not dangerous is unworthy of being called an idea at all.','Oscar Wilde',1,2);
insert into NOTES_TABLE values (8, NOW () ,3,'Be less curious about people and more curious about ideas.','Marie Curie!!!',1,2);
insert into NOTES_TABLE values (9, NOW () ,2,'All morning I struggled with the sensation of stray wisps of one world seeping through the cracks of another. Do you know the feeling when you start reading a new book before the membrane of the last one has had time to close behind you? You leave the previous book with ideas and themes -- characters even -- caught in the fibers of your clothes, and when you open the new book, they are still with you.','Diane Setterfield',1,2);
insert into NOTES_TABLE values (10, NOW () ,1,'I like the scientific spirit—the holding off, the being sure but not too sure, the willingness to surrender ideas when the evidence is against them: this is ultimately fine—it always keeps the way beyond open—always gives life, thought, affection, the whole man, a chance to try over again after a mistake—after a wrong guess.','Walt Whitman',1,2);
insert into NOTES_TABLE values (11, NOW () ,1,'For millions of years, mankind lived just like the animals. Then something happened which unleashed the power of our imagination. We learned to talk and we learned to listen. Speech has allowed the communication of ideas, enabling human beings to work together to build the impossible. Mankind''s greatest achievements have come about by talking, and its greatest failures by not talking. It doesn''t have to be like this. Our greatest hopes could become reality in the future. With the technology at our disposal, the possibilities are unbounded. All we need to do is make sure we keep talking.','Stephen Hawking',1,2);
insert into NOTES_TABLE values (12, NOW () ,1,'No army can withstand the strength of an idea whose time has come.','Victor Hugo',1,2);
insert into NOTES_TABLE values (13, NOW () ,1,'It''s okay to disagree with the thoughts or opinions expressed by other people. That doesn''t give you the right to deny any sense they might make. Nor does it give you a right to accuse someone of poorly expressing their beliefs just because you don''t like what they are saying. Learn to recognize good writing when you read it, even if it means overcoming your pride and opening your mind beyond what is comfortable.','Ashly Lorenzana',1,2);
insert into NOTES_TABLE values (14, NOW () ,1,'Gods die. And when they truly die they are unmourned and unremembered. Ideas are more difficult to kill than people, but they can be killed, in the end.','Neil Gaiman',1,2);
insert into NOTES_TABLE values (15, NOW () ,1,'If you haven''t found it yet, keep looking. Don''t settle. As with all matters of the heart, you''ll know when you find it. And, like any great relationship, it just gets better and better as the years roll on.','Steve Jobs',1,2);
insert into NOTES_TABLE values (16, NOW () ,1,'If you have an apple and I have an apple and we exchange these apples then you and I will still each have one apple. But if you have an idea and I have an idea and we exchange these ideas, then each of us will have two ideas','George Bernard Shaw',1,2);
insert into NOTES_TABLE values (17, NOW () ,1,'There is something at the bottom of every new human thought, every thought of genius, or even every earnest thought that springs up in any brain, which can never be communicated to others, even if one were to write volumes about it and were explaining one''s idea for thirty-five years; there''s something left which cannot be induced to emerge from your brain, and remains with you forever; and with it you will die, without communicating to anyone perhaps the most important of your ideas.', 'Fyodor Dostoevsky',1,2);
insert into NOTES_TABLE values (18, NOW () ,1,'Ideas come from everything.','Alfred Hitchcock',1,2);
insert into NOTES_TABLE values (19, NOW () ,1,'The ideals which have always shone before me and filled me with joy are goodness, beauty, and truth.','Albert Einstein',1,2);
insert into NOTES_TABLE values (20, NOW () ,1,'The problem is that the people with the most ridiculous ideas are always the people who are most certain of them.','Bill Maher',1,2);
insert into NOTES_TABLE values (21, NOW () ,1,'If you want something new, you have to stop doing something old.','Peter Drucker',1,1);
insert into NOTES_TABLE values (22, NOW () ,2,'When a reader falls in love with a book, it leaves its essence inside him, like radioactive fallout in an arable field, and after that there are certain crops that will no longer grow in him, while other, stranger, more fantastic growths may occasionally be produced.','Salman Rushdie',1,1);
insert into NOTES_TABLE values (23, NOW () ,3,'Integrity is the ability to stand by an idea.','Ayn Rand',1,1);
insert into NOTES_TABLE values (24, NOW () ,1,'You are an explorer, and you represent our species, and the greatest good you can do is to bring back a new idea, because our world is endangered by the absence of good ideas. Our world is in crisis because of the absence of consciousness.','Terence McKenna',1,1);
insert into NOTES_TABLE values (25, NOW () ,2,'A man may die, nations may rise and fall, but an idea lives on. Ideas have endurance without death.','John F. Kennedy',1,1);
insert into NOTES_TABLE values (26, NOW () ,3,'There''s no flesh or blood within this cloak to kill. There''s only an idea. Ideas are bulletproof.','Alan Moore',1,1);
insert into NOTES_TABLE values (27, NOW () ,1,'Censorship is the child of fear and the father of ignorance.','Laurie Halse Anderson',1,1);
insert into NOTES_TABLE values (28, NOW () ,2,'Take up one idea. Make that one idea your life – think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success, that is way great spiritual giants are produced.','Swami Vivekananda',1,1);
insert into NOTES_TABLE values (29, NOW () ,3,'An idea that is developed and put into action is more important than an idea that exists only as an idea.','Buddha',1,1);
insert into NOTES_TABLE values (30, NOW () ,1,'Good ideas are common – what''s uncommon are people who''ll work hard enough to bring them about.','Ashleigh Brilliant',1,1);
insert into NOTES_TABLE values (31, NOW () ,2,'Don''t worry about people stealing your ideas. If your ideas are any good, you''ll have to ram them down people''s throats.','Howard Aiken',1,1);
insert into NOTES_TABLE values (32, NOW () ,3,'Often the difference between a successful person and a failure is not one has better abilities or ideas, but the courage that one has to bet on one''s ideas, to take a calculated risk – and to act.','Andre Malraux',1,1);
insert into NOTES_TABLE values (33, NOW () ,1,'Ideas are the beginning points of all fortunes.','Napoleon Hill',1,1);
insert into NOTES_TABLE values (34, NOW () ,2,'My ideas usually come not at my desk writing but in the midst of living.','Anais Nin',1,1);
insert into NOTES_TABLE values (35, NOW () ,3,'The ability to convert ideas to things is the secret of outward success.','Henry Ward Beecher',1,1);
insert into NOTES_TABLE values (36, NOW () ,1,'New ideas pass through three periods: 1) It can''t be done. 2) It probably can be done, but it''s not worth doing. 3) I knew it was a good idea all along!','Arthur C. Clarke',1,1);
insert into NOTES_TABLE values (37, NOW () ,2,'Ideas can be life-changing. Sometimes all you need to open the door is just one more good idea.','Jim Rohn',1,1);
insert into NOTES_TABLE values (38, NOW () ,3,'You have to have an idea of what you are going to do, but it should be a vague idea','Pablo Picasso',1,1);
insert into NOTES_TABLE values (39, NOW () ,1,'I know quite certainly that I myself have no special talent; curiosity, obsession and dogged endurance, combined with self-criticism, have brought me to my ideas.','Albert Einstein',1,1);
insert into NOTES_TABLE values (40, NOW () ,2 ,'Nothing is more dangerous than an idea when it is the only one you have.','Emile Chartier',1,1);

insert into TAG_TABLE values(1,'memories');
insert into TAG_TABLE values(2,'quote');
insert into TAG_TABLE values(3,'food');
insert into TAG_TABLE values(4,'life');
insert into TAG_TABLE values(5,'brain');
insert into TAG_TABLE values(6,'looking for');
insert into TAG_TABLE values (7,'idea');
insert into TAG_TABLE values (8,'philosophy');
insert into TAG_TABLE values (9,'important');
insert into TAG_TABLE values (10,'success');


insert into NOTES_TABLE_TAGS values (1,4);
insert into NOTES_TABLE_TAGS values (1,10);
insert into NOTES_TABLE_TAGS values (2,2);
insert into NOTES_TABLE_TAGS values (2,4);
insert into NOTES_TABLE_TAGS values (2,8);
insert into NOTES_TABLE_TAGS values (3,4);
insert into NOTES_TABLE_TAGS values (3,8);
insert into NOTES_TABLE_TAGS values (8,9);
insert into NOTES_TABLE_TAGS values (20,2);
insert into NOTES_TABLE_TAGS values (20,4);
insert into NOTES_TABLE_TAGS values (20,8);
